# Generated by Django 5.2.1 on 2025-05-18 05:51

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_at', models.DateField(auto_now=True, null=True, verbose_name='Fecha de Eliminación')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Creado por')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Modificado por')),
                ('deleted_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Eliminado por')),
                ('names', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombres')),
                ('last_names', models.CharField(blank=True, max_length=150, null=True, verbose_name='Apellidos')),
                ('cedula', models.IntegerField(unique=True, verbose_name='Cedula')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_at', models.DateField(auto_now=True, null=True, verbose_name='Fecha de Eliminación')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Creado por')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Modificado por')),
                ('deleted_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Eliminado por')),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Especialidad')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctores',
            },
        ),
        migrations.CreateModel(
            name='HistorialMedico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_at', models.DateField(auto_now=True, null=True, verbose_name='Fecha de Eliminación')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Creado por')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Modificado por')),
                ('deleted_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Eliminado por')),
                ('doctores', models.ManyToManyField(related_name='historiale_atendidos', to='paciente.doctor')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiales', to='paciente.paciente')),
            ],
            options={
                'verbose_name': 'Historial Medico',
                'verbose_name_plural': 'Historiales Medicos',
            },
        ),
        migrations.CreateModel(
            name='DocumentoMedico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_at', models.DateField(auto_now=True, null=True, verbose_name='Fecha de Eliminación')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Creado por')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Modificado por')),
                ('deleted_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Eliminado por')),
                ('nombre_archivo', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre del Archivo')),
                ('archivo', models.FileField(upload_to='documentos_medicos/', verbose_name='Archivo')),
                ('historial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='paciente.historialmedico')),
            ],
            options={
                'verbose_name': 'Documento Medico',
                'verbose_name_plural': 'Documentos Medicos',
            },
        ),
        migrations.CreateModel(
            name='HistoricalPaciente',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificación')),
                ('deleted_at', models.DateField(blank=True, editable=False, null=True, verbose_name='Fecha de Eliminación')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Creado por')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Modificado por')),
                ('deleted_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Eliminado por')),
                ('names', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombres')),
                ('last_names', models.CharField(blank=True, max_length=150, null=True, verbose_name='Apellidos')),
                ('cedula', models.IntegerField(db_index=True, verbose_name='Cedula')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Paciente',
                'verbose_name_plural': 'historical Pacientes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
